-- 1. Criação da tabela de vendas


CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor)
VALUES
('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');


-- Exercício A - Liste todos os produtos vendidos por “Ana”, ordenados por data.

SELECT PRODUTO, DATA_VENDA, VALOR FROM VENDAS
WHERE VENDEDOR = 'Ana'
ORDER BY DATA_VENDA DESC;

-- Exercício B - Mostre o valor total vendido na categoria “Eletrônicos”.

SELECT SUM(VALOR) AS VALOR_TOTAL_VENDIDO FROM vendas
WHERE CATEGORIA = 'Eletrônicos';

-- Exercício C - Quais produtos custam entre R$200 e R$1000? Mostre nome e valor.

SELECT PRODUTO,VALOR FROM vendas
WHERE VALOR BETWEEN 200 AND 1000;

-- Exercicio D - Mostre quantas vendas cada vendedor realizou e o valor total vendido por ele, ordenado do maior para o menor faturamento.

SELECT VENDEDOR, COUNT(*) AS QTD_VENDIDA, SUM(VALOR) AS TOTAL_VENDIDO FROM VENDAS
GROUP BY VENDEDOR
ORDER BY QTD_VENDIDA DESC