CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');

-- Liste todos os produtos mais caros do que o produto mais barato da categoria "Eletrônicos".


SELECT PRODUTO, VALOR,  CATEGORIA FROM (
    SELECT PRODUTO, VALOR, CATEGORIA 
    FROM VENDAS 
    WHERE VALOR >( SELECT MIN(VALOR) FROM VENDAS WHERE CATEGORIA = 'Eletrônicos')

);


-- Mostre o vendedor que realizou a maior venda registrada na tabela.
SELECT VENDEDOR, VALOR
FROM VENDAS
WHERE VALOR = (SELECT MAX(VALOR) FROM VENDAS);



-- Liste as categorias que têm pelo menos um produto acima do preço médio geral.

SELECT CATEGORIA, PRODUTO, VALOR
FROM VENDAS 
WHERE VALOR > (SELECT AVG(VALOR) FROM VENDAS );

-- Monte um ranking dos 3 produtos mais caros vendidos por cada vendedor.
SELECT PRODUTO, VALOR, VENDEDOR
FROM (
    SELECT PRODUTO, VALOR, VENDEDOR,
           ROW_NUMBER() OVER (PARTITION BY VENDEDOR ORDER BY VALOR DESC) AS RN
    FROM VENDAS
) 
WHERE RN <= 3;