
CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');


CREATE TABLE CLIENTES (
    id_cliente    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(100) NOT NULL,
    cidade        VARCHAR2(50),
    estado        VARCHAR2(2)
);

-- 2. Inserção de clientes
INSERT INTO CLIENTES (nome, cidade, estado) VALUES
    ('Ana', 'São Paulo', 'SP'),
    ('Bruna', 'Campinas', 'SP'),
    ('Carlos', 'Rio de Janeiro', 'RJ');

ALTER TABLE VENDAS ADD id_cliente NUMBER;
ALTER TABLE VENDAS ADD CONSTRAINT fk_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente);

UPDATE VENDAS
SET id_cliente = CASE vendedor
    WHEN 'Ana' THEN 1
    WHEN 'Bruna' THEN 2
    WHEN 'Carlos' THEN 3
END;

-- ## Estudo de Caso: Relatório Gerencial “Clientes e Suas Vendas”

-- ### Missão:

-- Crie um relatório consolidado que mostre:

-- - Nome do cliente
-- - Cidade
-- - Quantidade de vendas realizadas
-- - Valor total
-- - Ticket médio

-- Liste o nome do cliente e o produto de cada venda, mostrando também a cidade.

SELECT c.nome,v.produto, c.CIDADE
FROM CLIENTES c
INNER JOIN VENDAS v
ON c.ID_CLIENTE = v.ID;

SELECT * FROM VENDAS;

-- Mostre o total de vendas por estado.
SELECT c.ESTADO, COUNT(c.ESTADO) AS QTD_VENDIDO 
FROM CLIENTES c 
INNER JOIN VENDAS v
ON c.ID_CLIENTE = v.ID
GROUP BY c.ESTADO
ORDER BY QTD_VENDIDO DESC;

-- Quais cidades tiveram mais de R$ 2.000,00 em vendas no total?
SELECT c.CIDADE, SUM(v.VALOR) AS QTD_VENDIDO 
FROM CLIENTES c 
INNER JOIN VENDAS v
ON c.ID_CLIENTE = v.ID
HAVING QTD_VENDIDO > 2000
GROUP BY c.CIDADE;

-- Exiba, para cada cliente, a categoria em que ele mais comprou (por valor total).

SELECT c.NOME, v.CATEGORIA, MAX(v.VALOR) AS VALOR_PRODUTO
FROM CLIENTES c 
INNER JOIN VENDAS v
ON c.ID_CLIENTE = v.ID
GROUP BY c.NOME, v.CATEGORIA
ORDER BY VALOR_PRODUTO 
